# -*- coding: utf-8 -*-
"""Chapter 10 Prog.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nBg3Yri5OuU-tsWQaKQZZn0WAmQCxDT1
"""

import tkinter
import tkinter.messagebox as msgbox

#Clean UI Design
def clean_ui(root):
    for widgets in  root.winfo_children():
        if widgets.winfo_class() != 'Menu':
            widgets.destroy()

def save_all_info():
    alphausername = root_e1.get()
    alphapassword = root_e2.get()
    alphakey = root_e3.get()
    betausername = root_e12.get()
    betapassword = root_e22.get()
    text_disp = ""
    if len(betausername) > 0:
        text_disp += "Beta Username: "+betausername
    if len(betapassword) > 0:
        text_disp += ", Beta Password: "+betapassword

    if len(alphausername) > 0:
        text_disp += ", Alpha Username: "+alphausername
    if len(alphapassword) > 0:
        text_disp += ", Alpha Password: "+alphapassword
    if len(alphakey) > 0:
        text_disp += " and Alpha Key: "+alphakey

    if chkbutton_Var1.get() == 1:
        text_disp += ", \n Option 1 selected"
    if chkbutton_Var2.get() == 1:
        text_disp += ", \n Option 2 selected"

    if radiobutton_Var1.get()=="1":
        text_disp += ", Goto step 3 selected"
    if radiobutton_Var1.get()=="2":
        text_disp += ", Goto step 7 selected"

    if scale_var1.get()>0:
        text_disp += ", Rating given: "+str(int(scale_var1.get()))
    #get list of selected items:
    for i in mylist.curselection():
        text_disp += ", "+mylist.get(i)

    if len(text_disp) < 1:
        text_disp = "NONE"

    tkinter.messagebox.showinfo("Information Saved",
                                "Following information have been saved for the current session only: \n" + text_disp)

def file_new_design():
    root_label0 = tkinter.Label(root, text="Enter Database Alpbha Details")
    root_label0.place(x=60, y=10)

    root_label1 = tkinter.Label(root, text="Your Username: ")
    root_label1.place(x=30, y=30)
    root_e1 = tkinter.Entry(root, show=None, font=('Arial', 8), bg='pink', fg="green")  # Display in text form
    root_e1.place(x=130, y=30)

    root_label2 = tkinter.Label(root, text="Your Password: ")
    root_label2.place(x=30, y=55)
    root_e2 = tkinter.Entry(root, show='*', font=('Arial', 8), bg='pink', fg="green")  # Display in ciphertext form
    root_e2.place(x=130, y=55)

    root_label3 = tkinter.Label(root, text="8 Digit Access Key: ")
    root_label3.place(x=30, y=80)
    root_e3 = tkinter.Entry(root, width=22, show=None, font=('Arial', 8), bg='pink', fg="green")  # Display in text form
    root_e3.place(x=200, y=80)

    root.mainloop()
def run_sample():
    msgbox.showwarning("Not Implemented","Just a sample function to handle all the events")
#Create UI Design
def createmenu(root):
    menubar = tkinter.Menu(root)
    himenu = tkinter.Menu(menubar, tearoff=0)
    himenu.add_command(label="Alpha Demo Data", command=run_sample)
    menubar.add_cascade(label="Database Alpha", menu=himenu)

    dcmenu = tkinter.Menu(menubar, tearoff=0)
    dcmenu.add_command(label="Beta Demo Data", command=run_sample)
    menubar.add_cascade(label="Database Beta", menu=dcmenu)

    etmenu = tkinter.Menu(menubar, tearoff=0)
    etmenu.add_command(label="New", command= file_new)
    etmenu.add_command(label="Open", command=run_sample)
    etmenu.add_command(label="Save", command=run_sample)
    menubar.add_cascade(label="File", menu=etmenu)

    etmenu = tkinter.Menu(menubar, tearoff=0)
    etmenu.add_command(label="Run", command = run_sample)
    etmenu.add_command(label="View", command=run_sample)
    etmenu.add_command(label="Analyze", command=run_sample)
    etmenu.add_command(label="Publish", command=run_sample)
    menubar.add_cascade(label="Audit Reports", menu=etmenu)

    etmenu = tkinter.Menu(menubar, tearoff=0)
    etmenu.add_command(label="Report 1: Bi-weekly Report", command=run_sample)
    etmenu.add_command(label="Report 2: Failed Tasks", command=run_sample)
    etmenu.add_command(label="Report 3: Monthly")
    etmenu.add_command(label="Report 4: Annual", command=run_sample)

    menubar.add_cascade(label="Custom Reports", menu=etmenu)
    root.config(menu=menubar)

def file_new():
    clean_ui(root)  #remove the existing widgets
    file_new_design()  # add new set of widgets


if __name__ =="__main__":

    root = tkinter.Tk()
    root.geometry('700x550')
    root.title("Reporting and Analysis Application")
    createmenu(root) #we will add the tool bar in this function later
    root_label0 = tkinter.Label(root, text="Enter Database Alpbha Details")
    root_label0.place(x=60, y=10)

    root_label1 = tkinter.Label(root, text="Your Username: ")
    root_label1.place(x=30, y=30)
    root_e1 = tkinter.Entry(root, show=None, font=('Arial', 8), bg='pink', fg="green")  # Display in text form
    root_e1.place(x=150, y=30)

    root_label2 = tkinter.Label(root, text="Your Password: ")
    root_label2.place(x=30, y=55)
    root_e2 = tkinter.Entry(root, show='*', font=('Arial', 8), bg='pink', fg="green")  # Display in ciphertext form
    root_e2.place(x=150, y=55)

    root_label3 = tkinter.Label(root, text="8 Digit Access Key: ")
    root_label3.place(x=30, y=80)
    root_e3 = tkinter.Entry(root, width= 22, show=None, font=('Arial', 8), bg='pink', fg="green")  # Display in text form
    root_e3.place(x=150, y=80)

    root_label02 = tkinter.Label(root, text="Enter Database Beta Details")
    root_label02.place(x=60, y=140)

    root_label12 = tkinter.Label(root, text="Your Username: ")
    root_label12.place(x=30, y=165)
    root_e12 = tkinter.Entry(root, show=None, font=('Arial', 8), bg='pink', fg="green")  # Display in text form
    root_e12.place(x=150, y=165)

    root_label22 = tkinter.Label(root, text="Your Password: ")
    root_label22.place(x=30, y=190)
    root_e22 = tkinter.Entry(root, show='*', font=('Arial', 8), bg='pink', fg="green")  # Display in ciphertext form
    root_e22.place(x=150, y=190)

    #Check button
    chkbutton_Var1 = tkinter.IntVar()
    chkbutton_Var2 = tkinter.IntVar()

    ChkBttn = tkinter.Checkbutton(root,text = "Select Option1", width=15, variable=chkbutton_Var1)
    ChkBttn.place(x=130, y=210)

    ChkBttn2 = tkinter.Checkbutton(root, text = "Select Option2",width=15, variable=chkbutton_Var2)
    ChkBttn2.place(x=130, y=230)

    #Radio button
    radiobutton_Var1 = tkinter.StringVar()
    RBttn = tkinter.Radiobutton(root, text="Goto Step 3", variable=radiobutton_Var1,value=1)
    RBttn.place(x=30, y=260)
    RBttn2 = tkinter.Radiobutton(root, text="Goto Step 7", variable=radiobutton_Var1,value=2)
    RBttn2.place(x=170, y=260)

    #Scale implementation
    scale_label1 = tkinter.Label(root, text="Give your rating (1-10): ")
    scale_label1.place(x=30, y=290)
    scale_var1 = tkinter.DoubleVar()
    scale = tkinter.Scale(root, variable=scale_var1, from_=1, to=10, orient=tkinter.HORIZONTAL)
    scale.place(x=170, y=290)
    #Scrollbar linked to a Listbox
    scrollbar = tkinter.Scrollbar(root)
    scrollbar.place(x=200, y=340)

    mylist = tkinter.Listbox(root, yscrollcommand=scrollbar.set)
    for line in range(100):
        mylist.insert(tkinter.END, "This is line number " + str(line))

    mylist.place(x=310, y=320)
    scrollbar.config(command=mylist.yview)

    #Save info
    root_button1 = tkinter.Button(root, text="Save my info for this session", command=save_all_info)
    root_button1.place(x=30,y=425)

    root.mainloop()